version: '3'

services:
  mysql-standalone1:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=chaos
      - MYSQL_DATABASE=spe
      - MYSQL_USER=keshavSpring
      - MYSQL_PASSWORD=Chaos!123
  central-hub-container:
    image: central-hub-image
    ports:
      - 9090:9090
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone1

